app:
  gitHubUrl: https://api.github.com
  stackOverflowUrl: https://api.stackexchange.com/2.3
  bot: http://localhost:8090
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  rate-limiter:
    enable: true
    limit: 120
    refill-per-minute: 120
  retry:
      type: fixed
      max-attempts: 3
      delay: 10000
      codes: 429, 500, 501, 502, 503, 504


spring:
  application:
    name: scrapper
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
