global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
        labels:
          application: 'bot'

  - job_name: 'scrapper'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'scrapper'
